# Generated by Django 3.0.7 on 2020-08-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('feedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.FeedItem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
