# Generated by Django 3.0.7 on 2020-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='username',
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
