# Generated by Django 3.0.7 on 2020-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200820_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
