# Generated by Django 3.0.7 on 2020-08-06 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
