# Generated by Django 3.0.7 on 2020-08-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200810_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to=''),
        ),
    ]
