# Generated by Django 3.0.7 on 2020-08-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20200830_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
